import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseProject, projectFrames, projectVisualScenes, sceneTimeline} from '../src/project/schema';

const raw = JSON.parse(readFileSync('projects/kyoto-travel-reel.json', 'utf8'));
const project = parseProject(raw);
assert.equal(project.template, 'travel-story');
assert.equal(project.format, 'vertical');
assert.equal(project.fps, 30);
const seconds = projectFrames(project) / project.fps;
assert.ok(seconds >= 39 && seconds <= 41, `Travel reel length: ${seconds}s`);
assert.equal(project.scenes.length, 9);
assert.equal(project.scenes.filter(s => s.type === 'travel-reel-highlight').length, 4);
assert.ok(project.scenes.some(s => s.type === 'geo-route'));
assert.ok(project.scenes.some(s => s.type === 'editorial-map'));
assert.ok(project.scenes.some(s => s.type === 'route-chapter'));
const route = project.geoRoutes?.['higashiyama-walk'];
assert.ok(route && route.coordinates.length >= 30 && route.source.license === 'ODbL 1.0');
assert.ok(project.scenes.every(s => !('src' in s) && !('photoSrc' in s)));
assert.equal(projectVisualScenes(project).length, 9);
const captions = project.reelCaptions?.captions ?? [];
assert.equal(captions.length, project.scenes.length * 2);
assert.equal(project.reelCaptions?.captionStyle, 'tiktok');
assert.ok(captions.every((s, i) => s.start >= 0 && s.end > s.start && s.end <= seconds && (i === 0 || s.start >= captions[i-1].end)));
const ranges = sceneTimeline(project);
assert.equal(ranges.length, 9);
const layout = readFileSync('src/remotion/CaptionOverlay.tsx', 'utf8');
assert.match(layout, /safeArea === 'vertical-reel'/);
assert.match(layout, /'23%'/);
assert.match(layout, /'17%'/);
const compositor = readFileSync('src/remotion/VideoComposition.tsx', 'utf8');
assert.match(compositor, /project\.reelCaptions/);
assert.match(compositor, /<CaptionOverlay/);
const renderer = readFileSync('src/remotion/scenes/TravelReelHighlightScene.tsx', 'utf8');
assert.match(renderer, /projectGeoPath/);
assert.match(renderer, /snapReelStop/);
assert.doesNotMatch(renderer, /\b(fetch|setTimeout|Math\.random)\s*\(/);
console.log(`Kyoto Travel Reel: 9 scenes, 4 SVG landmarks, 39.7s approx., ${captions.length} timed caption pages, 0 media assets.`);
