import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseProject,projectFrames,sceneTimeline} from '../src/project/schema';
const p=parseProject(JSON.parse(readFileSync('projects/kyoto-after-dark.json','utf8')));
const shots=['arrival','lantern','pagoda','teahouse','finale'];
assert.equal(p.format,'vertical');
assert.equal(p.fps,30);
assert.equal(projectFrames(p),1350,'Kyoto After Dark must be exactly 45s');
assert.deepEqual(p.scenes.map(s=>s.type==='animate-canvas'?s.cinematicShot:null),shots);
assert.equal(sceneTimeline(p).length,5);
assert.ok(p.scenes.every(s=>s.type==='animate-canvas'));
console.log('Kyoto After Dark: 5 unique vertical shots, 1350 frames, 45s.');
